// Generated by CoffeeScript 1.6.3
(function() {
  var Gtk, Wnck, currentWorkspace, log, screen, windows;

  Gtk = imports.gi.Gtk;

  Gtk.init(null, 0);

  log = function(msg) {
    throw msg;
  };

  Wnck = imports.gi.Wnck;

  screen = Wnck.Screen.get_default();

  windows = screen.get_windows();

  currentWorkspace = screen.get_active_workspace();

  windows = windows.filter(function(wnckWindow) {
    return wnckWindow.is_visible_on_workspace(currentWorkspace);
  });

  log(windows.length);

  windows[0].set_geometry(0, 15, 0, 0, 683, 768 - 27);

  windows[1].set_geometry(0, 15, 683, 0, 683, 768 - 27);

}).call(this);
