// Generated by CoffeeScript 1.6.3
var Config, Extension, ExtensionUtils, helper;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

Config = (function() {
  function Config() {
    var HOME, PATH, config;
    HOME = helper.spawnSync("sh -c 'echo $HOME'");
    PATH = (HOME + '/.twm').replace('\n', '');
    helper.log(PATH);
    imports.searchPath.push(PATH);
    config = imports.twm.config;
    helper.log(config);
  }

  /*
  Cp config/defalut.js to ~/.twm/twm.js
  
  @private
  */


  Config.prototype.create = function() {
    return false;
  };

  return Config;

})();
