// Generated by CoffeeScript 1.6.3
var Extension, ExtensionUtils, config, helper, keybindings, myLayouts, onStartup;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

onStartup = function() {
  return false;
};

keybindings = [];

myLayouts = [];

helper.log("helper!");

config = {
  onStartup: onStartup,
  layouts: myLayouts,
  keybindings: keybindings
};
