// Generated by CoffeeScript 1.7.1
var ConfigManager, Extension, ExtensionUtils, Wnck, disable, enable, helper, init, keybindings;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

keybindings = Extension.imports.lib.keybindings;

ConfigManager = Extension.imports.config.configManager.ConfigManager;

Wnck = imports.gi.Wnck;

init = function() {
  var callback, config, e, keybinding, onWindowChange, screen, _ref;
  global.twm = {
    functions: {}
  };
  try {
    config = new ConfigManager;
    _ref = config.keybindings;
    for (keybinding in _ref) {
      callback = _ref[keybinding];
      keybindings.add(keybinding, callback);
    }
    keybindings.apply();
    if (typeof config.onStartup === "function") {
      config.onStartup();
    }
    onWindowChange = function(wnckScreen, wnckWindow) {
      var currentLayout, currentWorkspace;
      wnckScreen.force_update();
      currentWorkspace = wnckScreen.get_active_workspace();
      if (wnckWindow.is_visible_on_workspace(currentWorkspace)) {
        if (config.windowsFilter(wnckWindow)) {
          currentLayout = config.layouts.current();
          if ((currentLayout != null) && currentLayout !== 'float') {
            config.layouts.apply(currentLayout, config.windowsFilter);
          }
        }
      }
      return false;
    };
    screen = Wnck.Screen.get_default();
    screen.connect("window-opened", onWindowChange);
    screen.connect("window-closed", onWindowChange);
  } catch (_error) {
    e = _error;
    global.log(e);
    helper.log(e);
  }
  return false;
};

enable = function() {
  return false;
};

disable = function() {
  return false;
};
