// Generated by CoffeeScript 1.7.1
var ConfigManager, Extension, ExtensionUtils, WindowManager, Wnck, disable, enable, helper, init, keybindings;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

keybindings = Extension.imports.lib.keybindings;

ConfigManager = Extension.imports.config.configManager.ConfigManager;

WindowManager = Extension.imports.lib.windowManager.WindowManager;

Wnck = imports.gi.Wnck;

init = function() {
  var callback, config, e, keybinding, _ref;
  global.twm = {
    functions: {}
  };
  global.twm.storage = {};
  try {
    config = new ConfigManager;
    helper.spawn("gsettings set org.gnome.shell.overrides dynamic-workspaces false");
    helper.spawn("gsettings set org.gnome.desktop.wm.preferences num-workspaces " + config.workspaceNum);
    _ref = config.keybindings;
    for (keybinding in _ref) {
      callback = _ref[keybinding];
      keybindings.add(keybinding, callback);
    }
    keybindings.apply();
    config.layouts.init();
    if (typeof config.onStartup === "function") {
      config.onStartup();
    }
  } catch (_error) {
    e = _error;
    global.log(e);
    helper.log(e);
  }
  return false;
};

enable = function() {
  return false;
};

disable = function() {
  return false;
};
