// Generated by CoffeeScript 1.7.1
var GLib, Main, MessageTray, delay, getXServerTimestamp, log, spawn, spawnSync;

Main = imports.ui.main;

MessageTray = imports.ui.messageTray;

GLib = imports.gi.GLib;

log = function(text) {
  var notification, source;
  if (typeof text !== "string") {
    text = JSON.stringify(text);
  }
  source = new MessageTray.SystemNotificationSource();
  Main.messageTray.add(source);
  notification = new MessageTray.Notification(source, text, null);
  notification.setTransient(true);
  return source.notify(notification);
};

spawn = function(cmd) {
  return GLib.spawn_command_line_async(cmd);
};

spawnSync = function(cmd) {
  var result;
  result = GLib.spawn_command_line_sync(cmd);
  if (result[0]) {
    return result[1].toString();
  } else {
    return log(result);
  }
};

delay = function(time, callback) {
  return GLib.timeout_add(GLib.PRIORITY_DEFAULT, time, function() {
    return typeof callback === "function" ? callback() : void 0;
  });
};

getXServerTimestamp = function() {
  return parseInt(GLib.get_monotonic_time() / 1000);
};
