// Generated by CoffeeScript 1.7.1
var Extension, ExtensionUtils, ScriptManager;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

ScriptManager = (function() {
  function ScriptManager() {
    if (ScriptManager.instance != null) {
      return ScriptManager.instance;
    }
    ScriptManager.instance = this;
    return this;
  }

  ScriptManager.prototype.run = function(scriptName, args, callback) {
    var scriptId;
    return scriptId = (new Date()).getTime() + scriptName;
  };

  ScriptManager.prototype.gc = function(scriptId) {
    return spawn("sh -c \"ps -ef | grep " + gjsDir + " | grep " + timestamp + " | awk '{print $2}' | xargs kill -9\"");
  };

  return ScriptManager;

})();
