// Generated by CoffeeScript 1.6.3
var Extension, ExtensionUtils, config, defalutConfig, helper, onStartup;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

defalutConfig = Extension.imports.config["default-config"].config;

onStartup = function() {
  return false;
};

config = {};
