// Generated by CoffeeScript 1.6.3
var config, helper, myKeybindings, myLayouts, onStartup;

helper = Extension.imports.helper;

onStartup = function() {
  return false;
};

myKeybindings = [];

myLayouts = [];

helper.log("helper!");

config = {
  onStartup: onStartup,
  layouts: myLayouts,
  keybindings: myKeybindings
};
