// Generated by CoffeeScript 1.7.1
var ConfigManager, Extension, ExtensionUtils, ShellJS, defalutConfig, helper, spawn, spawnSync, uuid;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

uuid = Extension.uuid;

helper = Extension.imports.helper;

spawn = helper.spawn, spawnSync = helper.spawnSync;

defalutConfig = Extension.imports.config.defaultConfig.config;

ShellJS = imports.gi.ShellJS;

ConfigManager = (function() {
  function ConfigManager() {
    var Config, HOME, PATH, config, e, key, value;
    HOME = helper.spawnSync("sh -c 'echo $HOME'");
    PATH = (HOME + '/.twm').replace('\n', '');
    this.installImporter(PATH);
    Config = global.twm.Config;
    try {
      config = Config.imports.twm.config;
    } catch (_error) {
      e = _error;
      helper.log("ConfigManager: " + e);
      config = null;
    }
    if (config == null) {
      config = {};
    }
    for (key in defalutConfig) {
      value = defalutConfig[key];
      if (config[key] == null) {
        config[key] = value;
      }
    }
    return config;
  }


  /*
  Add imports for config
  
  @private
   */

  ConfigManager.prototype.installImporter = function(configPath) {
    global.twm.importsTargetObject = {};
    ShellJS.add_extension_importer('global.twm.importsTargetObject', 'imports', configPath);
    global.twm.Extension = {
      imports: Extension.imports
    };
    return global.twm.Config = {
      imports: global.twm.importsTargetObject.imports
    };
  };

  return ConfigManager;

})();
