// Generated by CoffeeScript 1.6.3
var Config, Extension, ExtensionUtils, defalutConfig, fs, helper, spawn;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

spawn = helper.spawn;

defalutConfig = Extension.imports.config.defalut.config;

fs = Extension.imports.api.fs.fs;

Config = (function() {
  function Config() {
    var HOME, PATH, filename, js;
    HOME = helper.spawnSync("sh -c 'echo $HOME'");
    PATH = (HOME + '/.twm').replace('\n', '');
    if (fs.existsSync(PATH + '/twm.js')) {
      js = fs.readFileSync(PATH + '/twm.js');
    } else if (fs.existsSync(PATH + '/twm.coffee')) {
      filename = PATH + '/twm.coffee';
      js = spawnSync("coffee -p " + filename);
    } else {
      this.create();
    }
    helper.log(config);
  }

  /*
  Cp config/defalut.js to ~/.twm/twm.js
  
  @private
  */


  Config.prototype.create = function() {
    return false;
  };

  return Config;

})();
