// Generated by CoffeeScript 1.6.3
var Config, Extension, ExtensionUtils, Window, defalutConfig, helper, layouts, spawn;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

spawn = helper.spawn;

Window = Extension.imports.api.window.Window;

layouts = Extension.imports.layouts.layouts;

defalutConfig = {
  keybindings: {
    "<Super>e": function() {
      return spawn("emacsclient -c");
    },
    "<Super>c": function() {
      return spawn("google-chrome");
    },
    "<Super>l": function() {
      return Main.lookingGlass.toggle();
    },
    "<Super>Return": function() {
      return spawn("gnome-terminal");
    },
    "<Super>k": function() {
      return (new Window()).current().destroy();
    },
    "<Super>r": function() {
      return init();
    }
  },
  layouts: layouts.list(),
  onWindowChange: function() {
    return false;
  }
};

Config = (function() {
  function Config() {
    var HOME, PATH, config;
    HOME = helper.spawnSync("sh -c 'echo $HOME'");
    PATH = (HOME + '/.twm').replace('\n', '');
    helper.log(PATH);
    imports.searchPath.push(PATH);
    config = imports.twm.config;
    helper.log(config);
  }

  /*
  Cp config/defalut.js to ~/.twm/twm.js
  
  @private
  */


  Config.prototype.create = function() {
    return false;
  };

  return Config;

})();
