// Generated by CoffeeScript 1.6.3
var Config, Extension, ExtensionUtils, defalutConfig, fs, helper, spawn, uuid;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

uuid = Extension.uuid;

helper = Extension.imports.helper;

spawn = helper.spawn;

defalutConfig = Extension.imports.config.defaultConfig.config;

fs = Extension.imports.api.fs;

Config = (function() {
  function Config() {
    var HOME, PATH, config, e, filename, js, key, value;
    HOME = helper.spawnSync("sh -c 'echo $HOME'");
    PATH = (HOME + '/.twm').replace('\n', '');
    if (fs.existsSync(PATH + '/twm.js')) {
      js = fs.readFileSync(PATH + '/twm.js');
    } else if (fs.existsSync(PATH + '/twm.coffee')) {
      filename = PATH + '/twm.coffee';
      js = spawnSync("coffee -p " + filename);
    } else {
      this.create();
    }
    try {
      config = (Function(js + ';return config;'))();
    } catch (_error) {
      e = _error;
      helper.log("Error found in your config file: " + e);
    }
    for (key in defalutConfig) {
      value = defalutConfig[key];
      if (config[key] == null) {
        config[key] = value;
      }
    }
    return config;
  }

  /*
  Cp config/defalut.js to ~/.twm/twm.js
  
  @private
  */


  Config.prototype.create = function() {
    return false;
  };

  return Config;

})();
