// Generated by CoffeeScript 1.6.3
var Extension, ExtensionUtils, config, defalutConfig, helper, myWindowsFilter, onStartup;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

helper = Extension.imports.helper;

defalutConfig = Extension.imports.config.defaultConfig.config;

onStartup = function() {
  return false;
};

myWindowsFilter = function(win) {
  return win.wmClass.indexOf('gimp' === -1);
};

config = {
  windowsFilter: myWindowsFilter
};
