// Generated by CoffeeScript 1.6.3
/*
2-Column Layout

@author Zeno Zeng

 -------
|       |
|   1   |
|       |
 -------

 -------
|   |   |
| 1 | 2 |
|   |   |
 -------

 -------
|   | 2 |
|   | - |
| 1 | 3 |
|   | - |
|   | 4 |
 -------
*/

var layout;

layout = function(num) {
  var areas, eachHeight, index, _i;
  if (num === 1) {
    return [
      {
        x: 0,
        y: 0,
        width: 1,
        height: 1
      }
    ];
  } else if (num === 2) {
    return [
      {
        x: 0,
        y: 0,
        width: 0.5,
        height: 1
      }, {
        x: 0.5,
        y: 0,
        width: 0.5,
        height: 1
      }
    ];
  } else {
    areas = [];
    areas.push({
      x: 0,
      y: 0,
      width: 0.5,
      height: 1
    });
    eachHeight = 1 / (num - 1);
    for (index = _i = 2; 2 <= num ? _i <= num : _i >= num; index = 2 <= num ? ++_i : --_i) {
      areas.push({
        x: 0.5,
        y: (index - 2) * eachHeight,
        width: 0.5,
        height: eachHeight
      });
    }
    return areas;
  }
};
