// Generated by CoffeeScript 1.6.3
/*
3-Column Layout

@author Zeno Zeng

 -------
|       |
|   1   |
|       |
 -------

 -------
|   |   |
| 1 | 2 |
|   |   |
 -------

 -----------
|   |   |   |
| 1 | 2 | 3 |
|   |   |   |
 -----------

 -----------
|   |   | 3 |
| 1 | 2 |---|
|   |   | 4 |
 -----------

 -----------
|   | 2 | 3 |
| 1 |---|---|
|   | 5 | 4 |
 -----------

 -----------
|   | 2 | 3 |
|   |   | - |
| 1 | - | 4 |
|   | 5 | - |
|   |   | 6 |
 -----------

-----------
|   | 2 | 3 |
|   | - | - |
| 1 | 5 | 4 |
|   | - | - |
|   | 7 | 6 |
 -----------
*/

var layout;

layout = function(num) {
  var areas;
  if (num === 1) {
    return [
      {
        x: 0,
        y: 0,
        width: 1,
        height: 1
      }
    ];
  } else if (num === 2) {
    return [
      {
        x: 0,
        y: 0,
        width: 0.5,
        height: 1
      }, {
        x: 0.5,
        y: 0,
        width: 0.5,
        height: 1
      }
    ];
  } else if (num === 3) {
    return [
      {
        x: 0,
        y: 0,
        width: 0.3333,
        height: 1
      }, {
        x: 0.3333,
        y: 0,
        width: 0.3333,
        height: 1
      }, {
        x: 0.6666,
        y: 0,
        width: 0.3333,
        height: 1
      }
    ];
  } else {
    areas = [];
    return areas.push({
      x: 0,
      y: 0,
      width: 0.3333,
      height: 1
    });
  }
};
