// Generated by CoffeeScript 1.6.3
var Layouts;

Layouts = (function() {
  function Layouts() {
    this.layouts = {};
  }

  /*
  Get Layout Func
  
  @param [String] layoutName Layout Name
  */


  Layouts.prototype.get = function(layoutName) {
    return this.layouts[layoutName];
  };

  /*
  Set Layout Func
  
  @param [String] layoutName Layout Name
  @param [Function] layoutFunc Layout Function
  */


  Layouts.prototype.set = function(layoutName, layoutFunc) {
    return this.layouts[layoutName] = layoutFunc;
  };

  /*
  List all avaliable layouts, returns an array like ["2-column", "3-column"]
  */


  Layouts.prototype.list = function() {
    var key, layouts, value, _ref;
    layouts = [];
    _ref = this.layouts;
    for (key in _ref) {
      value = _ref[key];
      layouts.push(key);
    }
    return layouts;
  };

  return Layouts;

})();
