// Generated by CoffeeScript 1.6.3
var Extension, ExtensionUtils, fs, spawnSync;

ExtensionUtils = imports.misc.extensionUtils;

Extension = ExtensionUtils.getCurrentExtension();

spawnSync = Extension.imports.helper.spawnSync;

fs = {};

/*
Read File Contents

@param [String] filename Absolute path of the file
*/


fs.readFileSync = function(filename) {
  return spawnSync("cat " + filename);
};

/*
Test whether file exists

@param [String] path Absolute path of the file
*/


fs.existsSync = function(path) {
  var exists, result;
  result = spawnSync("[ -f " + path + " ] && echo 'Found' || echo 'Not found'");
  return exists = result === 'Found';
};
